web:
  image: tutorial/nginx
  ports:
    - "80:80"
  volumes:
    - ./www:/var/www
    - ./docker/vhost.conf:/etc/nginx/sites-enabled/vhost.conf  
  links:
    - php
php:
  image: nmcteam/php56
  volumes:
    - ./docker/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./docker/php.ini:/etc/php5/fpm/php.ini
    - ./www:/var/www
  links:
    - db
db:
  image: mysql:5.6
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=123456
